# Generated by Django 3.0.7 on 2020-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_shop_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED')], default=1, max_length=500),
            preserve_default=False,
        ),
    ]
