# Generated by Django 3.0.7 on 2020-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
    ]
